In [ ]:
import numpy as np

sudogrid = [[5,3,0,0,7,0,0,0,0],
            [6,0,0,1,9,5,0,0,0],
            [0,9,8,0,0,0,0,6,0],
            [8,0,0,0,6,0,0,0,3],
            [4,0,0,8,0,3,0,0,1],
            [7,0,0,0,2,0,0,0,6],
            [0,6,0,0,0,0,2,8,0],
            [0,0,0,0,1,9,0,0,5],
            [0,0,0,0,0,0,0,0,0]]

print(np.matrix(sudogrid))

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 5 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 8 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 0 0]]


In [ ]:
def cek(row, column, number):
  global sudogrid
  #is the number appearing in the same row?
  for i in range(0,9):
    if sudogrid[row][i] == number:                #apakah nomor yang kita inputkan ada di baris yg sama?
      return False
  #is the number appearing in the same column?
  for i in range(0,9):
    if sudogrid[i][column] == number:
      return False
  #is the number appearing in the same square?
  mulaiX = (column // 3)*3                        # start dari mana dia si column di tiap kotak (section)
  mulaiY = (row // 3)*3
  for i in range(0, 3):
    for j in range(0, 3):
      if sudogrid[mulaiY+i][mulaiX+j] == number:
        return False

  return True


In [ ]:
def selesai():
  global sudogrid
  for row in range(0,9):
    for column in range(0,9):
      if sudogrid[row][column] == 0:
        for number in range(1,10):
          if cek(row, column, number):
            sudogrid[row][column] = number
            selesai()
            sudogrid[row][column] = 0
        return
  print(np.matrix(sudogrid))
  input('More possible solutions')

selesai()

In [62]:
import numpy as np
import random

sudogrid = [[5,3,0,0,7,0,0,0,0],
            [6,0,0,1,9,5,0,0,0],
            [0,9,8,0,0,0,0,6,0],
            [8,0,0,0,6,0,0,0,3],
            [4,0,0,8,0,3,0,0,1],
            [7,0,0,0,2,0,0,0,6],
            [0,6,0,0,0,0,2,8,0],
            [0,0,0,0,1,9,0,0,5],
            [0,0,0,0,0,0,0,0,0]]


def cetak(sudogrid):
  hasilcetak = ''
  for i in range(0,9):
    for j in range(0,9):
      hasilcetak += str(sudogrid[i][j]) + ' '
      if(j+1)%3==0 and j!=0 and j+1!=9:
        hasilcetak += '| '

      if(j == 8):
        hasilcetak += '\n'

      if(j == 8) and ((i+1)%3 == 0) and (i+1!=9):
        hasilcetak += '- - - - - - - - - - - \n'
  print(hasilcetak)

def cek(row, column, number):
  global sudogrid
  #is the number appearing in the same row?
  for i in range(0,9):
    if sudogrid[row][i] == number:                #apakah nomor yang kita inputkan ada di baris yg sama?
      return False

  #is the number appearing in the same column?
  for i in range(0,9):
    if sudogrid[i][column] == number:
      return False

  #is the number appearing in the same square?
  mulaiX = (column // 3) * 3                        # start dari mana dia si column di tiap kotak (section)
  mulaiY = (row // 3) * 3
  for i in range(0,3):
    for j in range(0,3):
      if sudogrid[mulaiY+i][mulaiX+j] == number:
        return False

  return True

def selesai():
  global sudogrid
  for row in range(0,9):
    for column in range(0,9):
      if sudogrid[row][column] == 0:
        for number in range(1,10):
          if cek(row, column, number):
            sudogrid[row][column] = number
            selesai()
            sudogrid[row][column] = 0
        return
  
  cetak(sudogrid)
  input('More possible solutions')

selesai()

5 3 4 | 6 7 8 | 1 9 2 
6 7 2 | 1 9 5 | 3 4 8 
1 9 8 | 3 4 2 | 5 6 7 
- - - - - - - - - - - 
8 5 9 | 7 6 1 | 4 2 3 
4 2 6 | 8 5 3 | 9 7 1 
7 1 3 | 9 2 4 | 8 5 6 
- - - - - - - - - - - 
9 6 1 | 5 3 7 | 2 8 4 
2 8 7 | 4 1 9 | 6 3 5 
3 4 5 | 2 8 6 | 7 1 9 

5 3 4 | 6 7 8 | 9 1 2 
6 7 2 | 1 9 5 | 3 4 8 
1 9 8 | 3 4 2 | 5 6 7 
- - - - - - - - - - - 
8 5 9 | 7 6 1 | 4 2 3 
4 2 6 | 8 5 3 | 7 9 1 
7 1 3 | 9 2 4 | 8 5 6 
- - - - - - - - - - - 
9 6 1 | 5 3 7 | 2 8 4 
2 8 7 | 4 1 9 | 6 3 5 
3 4 5 | 2 8 6 | 1 7 9 



In [59]:
import random
board =    [[0,0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0,0],
            [0,0,0,0,0,0,0,0,0]]

def cetak(sudogrid):
  hasilcetak = ''
  for i in range(0,9):
    for j in range(0,9):
      hasilcetak += str(sudogrid[i][j]) + ' '
      if(j+1)%3==0 and j!=0 and j+1!=9:
        hasilcetak += '| '

      if(j == 8):
        hasilcetak += '\n'

      if(j == 8) and ((i+1)%3 == 0) and (i+1!=9):
        hasilcetak += '- - - - - - - - - - - \n'
  return hasilcetak


def buat(board1: list):
    board = board1.copy()
    for i in range(0,9):
        for j in range(0,9):
            if(random.randint(1,7) >= 5):
              board[i][j] = random.randint(1,9)
              if (not cekbuat(board,i,j,board[i][j])):
                  board[i][j] = 0
    return board

def cekbuat(board,row, column, number):
    # print(*board,sep='\n')
  #is the number appearing in the same row?
    for i in range(0,9):
        if(i == column):
            break
        if board[row][i] == number:                #apakah nomor yang kita inputkan ada di baris yg sama?
      
            return False

    #is the number appearing in the same column?
    for i in range(0,9):
        if(i==row):
            break
        if board[i][column] == number:
      
            return False

    #is the number appearing in the same square?
    mulaiX = (column // 3) * 3                        # start dari mana dia si column di tiap kotak (section)
    mulaiY = (row // 3) * 3
    for i in range(0,3):
        for j in range(0,3):
            if(mulaiY+i==row and mulaiX+j==column):
                break
            if board[mulaiY+i][mulaiX+j] == number:
           
                return False

    return True

def cek(row, column, number):
  global sudogrid
  #is the number appearing in the same row?
  for i in range(0,9):
    if sudogrid[row][i] == number:                #apakah nomor yang kita inputkan ada di baris yg sama?
      return False

  #is the number appearing in the same column?
  for i in range(0,9):
    if sudogrid[i][column] == number:
      return False

  #is the number appearing in the same square?
  mulaiX = (column // 3) * 3                        # start dari mana dia si column di tiap kotak (section)
  mulaiY = (row // 3) * 3
  for i in range(0,3):
    for j in range(0,3):
      if sudogrid[mulaiY+i][mulaiX+j] == number:
        return False

  return True

def selesai():
  global sudogrid
  for row in range(0,9):
    for column in range(0,9):
      if sudogrid[row][column] == 0:
        for number in range(1,10):
          if cek(row, column, number):
            sudogrid[row][column] = number
            selesai()
            sudogrid[row][column] = 0
        return
  
  print(cetak(sudogrid))
  input('More possible solutions')

board = buat(board)
print("Initial board:")
print(cetak(board))
sudogrid = board.copy()
print("Solution: ")
selesai()

Initial board:
6 0 9 | 5 0 0 | 0 0 0 
0 0 0 | 0 0 1 | 8 9 2 
7 0 5 | 4 9 0 | 0 6 0 
- - - - - - - - - - - 
0 1 2 | 3 0 0 | 7 0 0 
0 0 0 | 6 0 5 | 4 0 0 
0 7 8 | 0 0 0 | 6 0 0 
- - - - - - - - - - - 
0 2 0 | 1 0 0 | 0 0 6 
5 0 7 | 0 0 9 | 0 0 0 
0 3 0 | 0 0 7 | 0 2 0 

Solution: 
